// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: man.proto

package gen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArticleRequest_SelectType int32

const (
	ArticleRequest_SELECT_FULL ArticleRequest_SelectType = 0
	ArticleRequest_SELECT_HEAD ArticleRequest_SelectType = 1
	ArticleRequest_SELECT_TAIL ArticleRequest_SelectType = 2
)

// Enum value maps for ArticleRequest_SelectType.
var (
	ArticleRequest_SelectType_name = map[int32]string{
		0: "SELECT_FULL",
		1: "SELECT_HEAD",
		2: "SELECT_TAIL",
	}
	ArticleRequest_SelectType_value = map[string]int32{
		"SELECT_FULL": 0,
		"SELECT_HEAD": 1,
		"SELECT_TAIL": 2,
	}
)

func (x ArticleRequest_SelectType) Enum() *ArticleRequest_SelectType {
	p := new(ArticleRequest_SelectType)
	*p = x
	return p
}

func (x ArticleRequest_SelectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArticleRequest_SelectType) Descriptor() protoreflect.EnumDescriptor {
	return file_man_proto_enumTypes[0].Descriptor()
}

func (ArticleRequest_SelectType) Type() protoreflect.EnumType {
	return &file_man_proto_enumTypes[0]
}

func (x ArticleRequest_SelectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArticleRequest_SelectType.Descriptor instead.
func (ArticleRequest_SelectType) EnumDescriptor() ([]byte, []int) {
	return file_man_proto_rawDescGZIP(), []int{3, 0}
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardName     string                 `protobuf:"bytes,1,opt,name=board_name,json=boardName,proto3" json:"board_name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_man_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_man_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_man_proto_rawDescGZIP(), []int{0}
}

func (x *ListRequest) GetBoardName() string {
	if x != nil {
		return x.BoardName
	}
	return ""
}

func (x *ListRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	Entries       []*Entry               `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReply) Reset() {
	*x = ListReply{}
	mi := &file_man_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReply) ProtoMessage() {}

func (x *ListReply) ProtoReflect() protoreflect.Message {
	mi := &file_man_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReply.ProtoReflect.Descriptor instead.
func (*ListReply) Descriptor() ([]byte, []int) {
	return file_man_proto_rawDescGZIP(), []int{1}
}

func (x *ListReply) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

func (x *ListReply) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BoardName     string                 `protobuf:"bytes,1,opt,name=board_name,json=boardName,proto3" json:"board_name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	IsDir         bool                   `protobuf:"varint,4,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_man_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_man_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_man_proto_rawDescGZIP(), []int{2}
}

func (x *Entry) GetBoardName() string {
	if x != nil {
		return x.BoardName
	}
	return ""
}

func (x *Entry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *Entry) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Entry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

type ArticleRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	BoardName     string                    `protobuf:"bytes,1,opt,name=board_name,json=boardName,proto3" json:"board_name,omitempty"`
	Path          string                    `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	SelectType    ArticleRequest_SelectType `protobuf:"varint,3,opt,name=select_type,json=selectType,proto3,enum=pttbbs.man.ArticleRequest_SelectType" json:"select_type,omitempty"`
	CacheKey      string                    `protobuf:"bytes,4,opt,name=cache_key,json=cacheKey,proto3" json:"cache_key,omitempty"`
	Offset        int64                     `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	MaxLength     int64                     `protobuf:"varint,6,opt,name=max_length,json=maxLength,proto3" json:"max_length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleRequest) Reset() {
	*x = ArticleRequest{}
	mi := &file_man_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleRequest) ProtoMessage() {}

func (x *ArticleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_man_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleRequest.ProtoReflect.Descriptor instead.
func (*ArticleRequest) Descriptor() ([]byte, []int) {
	return file_man_proto_rawDescGZIP(), []int{3}
}

func (x *ArticleRequest) GetBoardName() string {
	if x != nil {
		return x.BoardName
	}
	return ""
}

func (x *ArticleRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ArticleRequest) GetSelectType() ArticleRequest_SelectType {
	if x != nil {
		return x.SelectType
	}
	return ArticleRequest_SELECT_FULL
}

func (x *ArticleRequest) GetCacheKey() string {
	if x != nil {
		return x.CacheKey
	}
	return ""
}

func (x *ArticleRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ArticleRequest) GetMaxLength() int64 {
	if x != nil {
		return x.MaxLength
	}
	return 0
}

type ArticleReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Content        []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	CacheKey       string                 `protobuf:"bytes,2,opt,name=cache_key,json=cacheKey,proto3" json:"cache_key,omitempty"`
	FileSize       int64                  `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	SelectedOffset int64                  `protobuf:"varint,4,opt,name=selected_offset,json=selectedOffset,proto3" json:"selected_offset,omitempty"`
	SelectedSize   int64                  `protobuf:"varint,5,opt,name=selected_size,json=selectedSize,proto3" json:"selected_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ArticleReply) Reset() {
	*x = ArticleReply{}
	mi := &file_man_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleReply) ProtoMessage() {}

func (x *ArticleReply) ProtoReflect() protoreflect.Message {
	mi := &file_man_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleReply.ProtoReflect.Descriptor instead.
func (*ArticleReply) Descriptor() ([]byte, []int) {
	return file_man_proto_rawDescGZIP(), []int{4}
}

func (x *ArticleReply) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ArticleReply) GetCacheKey() string {
	if x != nil {
		return x.CacheKey
	}
	return ""
}

func (x *ArticleReply) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *ArticleReply) GetSelectedOffset() int64 {
	if x != nil {
		return x.SelectedOffset
	}
	return 0
}

func (x *ArticleReply) GetSelectedSize() int64 {
	if x != nil {
		return x.SelectedSize
	}
	return 0
}

var File_man_proto protoreflect.FileDescriptor

const file_man_proto_rawDesc = "" +
	"\n" +
	"\tman.proto\x12\n" +
	"pttbbs.man\"@\n" +
	"\vListRequest\x12\x1d\n" +
	"\n" +
	"board_name\x18\x01 \x01(\tR\tboardName\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"W\n" +
	"\tListReply\x12\x1d\n" +
	"\n" +
	"is_success\x18\x01 \x01(\bR\tisSuccess\x12+\n" +
	"\aentries\x18\x02 \x03(\v2\x11.pttbbs.man.EntryR\aentries\"g\n" +
	"\x05Entry\x12\x1d\n" +
	"\n" +
	"board_name\x18\x01 \x01(\tR\tboardName\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x15\n" +
	"\x06is_dir\x18\x04 \x01(\bR\x05isDir\"\xa0\x02\n" +
	"\x0eArticleRequest\x12\x1d\n" +
	"\n" +
	"board_name\x18\x01 \x01(\tR\tboardName\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12F\n" +
	"\vselect_type\x18\x03 \x01(\x0e2%.pttbbs.man.ArticleRequest.SelectTypeR\n" +
	"selectType\x12\x1b\n" +
	"\tcache_key\x18\x04 \x01(\tR\bcacheKey\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x03R\x06offset\x12\x1d\n" +
	"\n" +
	"max_length\x18\x06 \x01(\x03R\tmaxLength\"?\n" +
	"\n" +
	"SelectType\x12\x0f\n" +
	"\vSELECT_FULL\x10\x00\x12\x0f\n" +
	"\vSELECT_HEAD\x10\x01\x12\x0f\n" +
	"\vSELECT_TAIL\x10\x02\"\xb0\x01\n" +
	"\fArticleReply\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x1b\n" +
	"\tcache_key\x18\x02 \x01(\tR\bcacheKey\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x03R\bfileSize\x12'\n" +
	"\x0fselected_offset\x18\x04 \x01(\x03R\x0eselectedOffset\x12#\n" +
	"\rselected_size\x18\x05 \x01(\x03R\fselectedSize2\x89\x01\n" +
	"\n" +
	"ManService\x128\n" +
	"\x04List\x12\x17.pttbbs.man.ListRequest\x1a\x15.pttbbs.man.ListReply\"\x00\x12A\n" +
	"\aArticle\x12\x1a.pttbbs.man.ArticleRequest\x1a\x18.pttbbs.man.ArticleReply\"\x00B\bZ\x06./;genb\x06proto3"

var (
	file_man_proto_rawDescOnce sync.Once
	file_man_proto_rawDescData []byte
)

func file_man_proto_rawDescGZIP() []byte {
	file_man_proto_rawDescOnce.Do(func() {
		file_man_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_man_proto_rawDesc), len(file_man_proto_rawDesc)))
	})
	return file_man_proto_rawDescData
}

var file_man_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_man_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_man_proto_goTypes = []any{
	(ArticleRequest_SelectType)(0), // 0: pttbbs.man.ArticleRequest.SelectType
	(*ListRequest)(nil),            // 1: pttbbs.man.ListRequest
	(*ListReply)(nil),              // 2: pttbbs.man.ListReply
	(*Entry)(nil),                  // 3: pttbbs.man.Entry
	(*ArticleRequest)(nil),         // 4: pttbbs.man.ArticleRequest
	(*ArticleReply)(nil),           // 5: pttbbs.man.ArticleReply
}
var file_man_proto_depIdxs = []int32{
	3, // 0: pttbbs.man.ListReply.entries:type_name -> pttbbs.man.Entry
	0, // 1: pttbbs.man.ArticleRequest.select_type:type_name -> pttbbs.man.ArticleRequest.SelectType
	1, // 2: pttbbs.man.ManService.List:input_type -> pttbbs.man.ListRequest
	4, // 3: pttbbs.man.ManService.Article:input_type -> pttbbs.man.ArticleRequest
	2, // 4: pttbbs.man.ManService.List:output_type -> pttbbs.man.ListReply
	5, // 5: pttbbs.man.ManService.Article:output_type -> pttbbs.man.ArticleReply
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_man_proto_init() }
func file_man_proto_init() {
	if File_man_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_man_proto_rawDesc), len(file_man_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_man_proto_goTypes,
		DependencyIndexes: file_man_proto_depIdxs,
		EnumInfos:         file_man_proto_enumTypes,
		MessageInfos:      file_man_proto_msgTypes,
	}.Build()
	File_man_proto = out.File
	file_man_proto_goTypes = nil
	file_man_proto_depIdxs = nil
}
